# Generated by Django 2.0 on 2018-04-15 16:55

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180415_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='num_slug',
            field=models.SmallIntegerField(default=1, validators=[main.validators.validate_num_slug]),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[main.validators.validate_title]),
        ),
    ]
